# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Tinnci.TPFanCtrl2
PackageVersion: 2.6.0
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
ElevationRequirement: elevationRequired
NestedInstallerFiles:
  - RelativeFilePath: TPFanCtrl2.exe
    PortableCommandAlias: TPFanCtrl2
  - RelativeFilePath: TPFanCtrl2-cli.exe
    PortableCommandAlias: TPFanCtrl2-cli
Commands:
  - TPFanCtrl2
  - TPFanCtrl2-cli
Installers:
  - Architecture: x86
    InstallerUrl: https://github.com/Tinnci/TPFanCtrl2/releases/download/v2.6.0/TPFanCtrl2-v2.6.0-windows-x86-app.zip
    InstallerSha256: 803303b27344c656730ba93918fbbe6de5abc15de84515c90f95bbf90802a73a
  - Architecture: x64
    InstallerUrl: https://github.com/Tinnci/TPFanCtrl2/releases/download/v2.6.0/TPFanCtrl2-v2.6.0-windows-x64-app.zip
    InstallerSha256: 3bf4f024e4c265960f2054067b6c4d4e18896d8e3c82fd9ae04279c96df6aeb7
Dependencies:
  PackageDependencies:
    - PackageIdentifier: namazso.PawnIO
      MinimumVersion: 2.2.0
ManifestType: installer
ManifestVersion: 1.6.0