# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Tinnci.TPFanCtrl2
PackageVersion: 2.7.0
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
ElevationRequirement: elevationRequired
NestedInstallerFiles:
  - RelativeFilePath: TPFanCtrl2.exe
    PortableCommandAlias: TPFanCtrl2
  - RelativeFilePath: TPFanCtrl2-cli.exe
    PortableCommandAlias: TPFanCtrl2-cli
Commands:
  - TPFanCtrl2
  - TPFanCtrl2-cli
Installers:
  - Architecture: x86
    InstallerUrl: https://github.com/Tinnci/TPFanCtrl2/releases/download/v2.7.0/TPFanCtrl2-v2.7.0-windows-x86-app.zip
    InstallerSha256: 5ee150cf8d4b130907bb0d6a5668f3a71ac6cde815c87fdcb80d1fb6ea925f42
  - Architecture: x64
    InstallerUrl: https://github.com/Tinnci/TPFanCtrl2/releases/download/v2.7.0/TPFanCtrl2-v2.7.0-windows-x64-app.zip
    InstallerSha256: 871b283cf8c4716a6d9f819357cb602f3593449d237aa9760348431b608b020a
Dependencies:
  PackageDependencies:
    - PackageIdentifier: namazso.PawnIO
      MinimumVersion: 2.2.0
ManifestType: installer
ManifestVersion: 1.6.0